### PR TITLE
changed signatures of methods and functions

### PR DESCRIPTION
**Pull request by HellishBro**
all users must update their code to reflect the changes on the next pip release.
also @SilkePilon please spell things correctly

### CODE REVIEW

**Comment by SilkePilon** [comment]
I don't think it's wise to change the names of in input variables. The mineflayer.createBot uses profileFolder. I think it's better to keep it the same

**Comment by HellishBro** [comment]
pep 8 style conventions says to only use snake case for variable names

**Comment by HellishBro** [comment]
> > pep 8 style conventions says to only use snake case for variable names
> 
> yeah, the internal vars can stay the same. only the input vars in the createbot need to stay the same as the normal mineflayer. so the docs match

we need a style guide

yeah mineflayer uses pascalcase, which is javascripts style guide. so ig parameters to mineflayer createbot can be pascalcase, but what abt lodestone only ones? like stop bot on death, etc

**Comment by HellishBro** [comment]
k making a new pr on the plugin update

**Pull request closed without merging**
